# Neighborhood-based


###### UserBase Detail


In [ ]:
import numpy as np
#[user][item]
a = np.array([[1, 4, 5, 0, 3],
             [5, 1, 0, 5, 2],
             [4, 1, 2, 5, 0],
             [0, 3, 4, 0, 4]])
a

array([[1, 4, 5, 0, 3],
       [5, 1, 0, 5, 2],
       [4, 1, 2, 5, 0],
       [0, 3, 4, 0, 4]])

In [ ]:
#Cosin thu cong:
users, items= a.shape
b = a.copy()
sim = []

for v1 in a:
  v = []
  for v2 in b:
       v.append(v1 @ v2 / (np.linalg.norm(v1) * np.linalg.norm(v2))) #Tinh goc giua 2 vector
  sim.append(v)


sim = np.array(sim)
sim

array([[1.        , 0.28322059, 0.37162806, 0.96222284],
       [0.28322059, 1.        , 0.91452919, 0.23164312],
       [0.37162806, 0.91452919, 1.        , 0.25329221],
       [0.96222284, 0.23164312, 0.25329221, 1.        ]])

In [ ]:
#Cosin Thu Vien = Cosin Thu Cong
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(a, a)

array([[1.        , 0.28322059, 0.37162806, 0.96222284],
       [0.28322059, 1.        , 0.91452919, 0.23164312],
       [0.37162806, 0.91452919, 1.        , 0.25329221],
       [0.96222284, 0.23164312, 0.25329221, 1.        ]])

In [ ]:
#Predict
k = 2
user = 4
item = 1
##########

In [ ]:
#Xep hang
user -= 1
item -= 1

user_predicted = [] #index - sim
for i in range(users):
  if a[i][item] != 0:
    user_predicted.append((i, sim[i][user]))

user_sorted = sorted(user_predicted, key=lambda x: x[1], reverse=True)
user_k = user_sorted[:k]
user_k

[(0, 0.9622228370495298), (2, 0.2532922144821772)]

In [ ]:
def R(user): #Diem du doan trung binh cua tung user
  len = 0
  sum = 0
  for it in range(items):
    if a[user][it] != 0:
      sum += a[user][it]
      len += 1

  return sum/len

In [ ]:
#Person Sim
top = 0
bot = 0
for i,sim in user_k:
  top +=  sim*(a[i][item] - R(i))
  bot += sim

predict = R(user) + top / bot
predict
R(user)

3.6666666666666665

## <1> UserBase

In [ ]:
#@title Input
a = np.array([[1, 4, 5, 0, 3],
             [5, 1, 0, 5, 2], #hang 2 va hang 3 tuong quan
             [4, 1, 2, 0, 0], #bo di so 5 de check xem du doan co gan voi 5 khong
             [0, 3, 4, 0, 4]])
#Predict
k = 2 #@param {type:""}
user = 3 #@param {type:""}
item = 4 #@param {type:""}
##########
a

array([[1, 4, 5, 0, 3],
       [5, 1, 0, 5, 2],
       [4, 1, 2, 0, 0],
       [0, 3, 4, 0, 4]])

In [ ]:
#@title Process
def R(user): #Diem du doan trung binh cua tung user
  len = 0
  sum = 0
  for it in range(items):
    if a[user][it] != 0:
      sum += a[user][it]
      len += 1

  return sum/len

def user_base(a, k, user, item):

  # Cosin thu cong:
  users, items= a.shape
  b = a.copy()
  sim = []

  for v1 in a:
    v = []
    for v2 in b:
        v.append(v1 @ v2 / (np.linalg.norm(v1) * np.linalg.norm(v2))) #Tinh goc giua 2 vector
    sim.append(v)
  sim = np.array(sim)

  # Cosin Thu Vien
  # from sklearn.metrics.pairwise import cosine_similarity
  # cosine_similarity(a, a)

  #Xep hang
  user -= 1
  item -= 1

  user_predicted = [] #index, sim
  for i in range(users):
    if a[i][item] != 0:
      user_predicted.append((i, sim[i][user]))

  user_sorted = sorted(user_predicted, key=lambda x: x[1], reverse=True)
  user_k = user_sorted[:k]

  #Person Sim
  top = 0
  bot = 0
  for i,sim in user_k:
    top +=  sim*(a[i][item] - R(i))
    bot += sim

  predict = R(user) + top / bot
  return predict

In [ ]:
#@title Output
user_base(a, k, user, item) #Ket qua gan voi so 5 da loai bo

4.083333333333334

## <2> Item base

In [ ]:
#@title Output
user, item = item, user
user_base(a.T, k, user, item) #Ket qua gan voi so 5 da loai bo

3.817734996501608

## <3> Baseline Predictor



In [ ]:
#@title Input
x = np.nan
a = np.array([[1, 4, 5, x, 3],
             [5, 1, x, 5, 2], #hang 2 va hang 3 tuong quan
             [4, 1, 2, x, x], #bo di so 5 de check xem du doan co gan voi 5 khong
             [x, 3, 4, x, 4]])
#Predict
user = 3 #@param {type:""}
item = 4 #@param {type:""}
##########
a

array([[ 1.,  4.,  5., nan,  3.],
       [ 5.,  1., nan,  5.,  2.],
       [ 4.,  1.,  2., nan, nan],
       [nan,  3.,  4., nan,  4.]])

In [ ]:
#@title Process
def baseline(a, user, item):

  _u = np.nanmean(a)
  bias_user = np.nanmean(a[user-1, :]) - _u
  bias_item = np.nanmean(a[:, item-1]) - _u

  return _u + bias_user + bias_item


In [ ]:
#@title Output
baseline(a, user, item) #Ket qua gan voi so 5 da loai bo

4.190476190476191

#Model-Base


##<4> Matrix factorization

In [56]:
import numpy as np
a =  np.array([[1, 4, 5, 0, 3],
              [5, 1, 0, 5, 2], #hang 2 va hang 3 tuong quan
              [4, 1, 2, 0, 0], #bo di so 5 de check xem du doan co gan voi 5 khong
              [0, 3, 4, 0, 4]])


#latent_factors
K = 2  #@param {type:""}

#leaning_rate
beta = 0.01 #@param {type:""}

#regularization
lamda = 0.02 #@param {type:""}

epos = 1000 #@param {type:""}
a

array([[1, 4, 5, 0, 3],
       [5, 1, 0, 5, 2],
       [4, 1, 2, 0, 0],
       [0, 3, 4, 0, 4]])

In [57]:
def matrix_factorization(a, K, beta, lamda, epos):
  users, items = a.shape

  W = np.random.rand(users, K)
  H = np.random.rand(items, K)


  # Training
  for step in range(epos):
      for u in range(users):
          for i in range(items):
              if a[u, i] > 0:
                  error = a[u, i] - np.dot(W[u, :], H[i, :])
                  for k in range(K):
                      W[u, k] += beta * (error * H[i, k] - lamda * W[u, k])
                      H[i, k] += beta * (error * W[u, k] - lamda * H[i, k])
      print('epos',step,'loss:',error)
  return np.dot(W, H.T)


In [58]:
matrix_factorization(a, K, beta, lamda, epos) #Ket qua a[3][4] gan voi so 5 da loai bo

epos 0 loss: 3.82454458707079
epos 1 loss: 3.7739560148622844
epos 2 loss: 3.713285738507867
epos 3 loss: 3.6413017244850154
epos 4 loss: 3.5570030810173026
epos 5 loss: 3.459757240753956
epos 6 loss: 3.349439842807251
epos 7 loss: 3.226553296060881
epos 8 loss: 3.0922960692844232
epos 9 loss: 2.948557769917125
epos 10 loss: 2.7978266191691135
epos 11 loss: 2.6430142320819012
epos 12 loss: 2.4872223185588385
epos 13 loss: 2.333490067340928
epos 14 loss: 2.184564329583365
epos 15 loss: 2.042726479033928
epos 16 loss: 1.909693834482387
epos 17 loss: 1.7865959912215628
epos 18 loss: 1.6740127802325606
epos 19 loss: 1.5720535495869203
epos 20 loss: 1.4804567957898191
epos 21 loss: 1.3986928098795892
epos 22 loss: 1.3260574861238892
epos 23 loss: 1.2617508542333211
epos 24 loss: 1.204938183737501
epos 25 loss: 1.1547943583486906
epos 26 loss: 1.1105337728944367
epos 27 loss: 1.0714286009141474
epos 28 loss: 1.0368182690111638
epos 29 loss: 1.00611263938023
epos 30 loss: 0.9787909409618365
e

array([[0.99988092, 3.95086865, 4.9111178 , 3.01496287, 3.05944739],
       [4.92504176, 0.89856406, 1.54360296, 4.96168042, 2.1598137 ],
       [3.98509767, 1.20156474, 1.82791587, 4.26752998, 2.07762358],
       [5.73763236, 2.94084156, 4.10910999, 6.78935925, 3.83346255]])

## <5> Matrix factorization Upgare

In [53]:
import numpy as np
x = np.nan
a =  np.array([[1, 4, 5, x, 3],
              [5, 1, x, 5, 2], #hang 2 va hang 3 tuong quan
              [4, 1, 2, x, x], #bo di so 5 de check xem du doan co gan voi 5 khong
              [x, 3, 4, x, 4]])


#latent_factors
K = 2  #@param {type:""}

#leaning_rate
beta = 0.01 #@param {type:""}

#regularization
lamda = 0.02 #@param {type:""}

epos = 1000 #@param {type:""}
a

array([[ 1.,  4.,  5., nan,  3.],
       [ 5.,  1., nan,  5.,  2.],
       [ 4.,  1.,  2., nan, nan],
       [nan,  3.,  4., nan,  4.]])

In [54]:
def matrix_factorization_upgare(a, K, beta, lamda, epos):

  users, items = a.shape

  W = np.random.rand(users, K)
  H = np.random.rand(items, K)

  #upgare
  _u = np.nanmean(a)

  bias_users = []
  bias_items = []
  for u in range(users):
    bias_users.append(np.nanmean(a[u, :]) - _u)

  for i in range(items):
    bias_items.append(np.nanmean(a[:, i]) - _u)
  #######

  a[np.isnan(a)] = 0
  print(a)
  # Training
  for step in range(epos):
      for u in range(users):
          for i in range(items):
              if a[u, i] > 0:

                  aui = _u + bias_users[u] + bias_items[i] + np.dot(W[u, :], H[i, :])

                  error = a[u, i] - aui
                  _u = _u + beta * error
                  bias_users[u] = bias_users[u] + beta * (error - lamda * bias_users[u])
                  bias_items[i] = bias_items[i] + beta * (error - lamda * bias_items[i])

                  for k in range(K):

                      W[u, k] += beta * (error * H[i, k] - lamda * W[u, k])
                      H[i, k] += beta * (error * W[u, k] - lamda * H[i, k])
      print('epos',step,'loss:',error)
  matrix = np.dot(W, H.T)
  for u in range(users):
    for i in range(items):
      matrix[u][i] += _u + bias_users[u] + bias_items[i]
  return matrix


In [55]:
matrix_factorization_upgare(a, K, beta, lamda, epos) #Ket qua a[3][4] gan voi so 5 da loai bo

[[1. 4. 5. 0. 3.]
 [5. 1. 0. 5. 2.]
 [4. 1. 2. 0. 0.]
 [0. 3. 4. 0. 4.]]
epos 0 loss: 0.4177213133065165
epos 1 loss: 0.46270512696387334
epos 2 loss: 0.49651476881260814
epos 3 loss: 0.5216723661021483
epos 4 loss: 0.5401321929647454
epos 5 loss: 0.5534112850465966
epos 6 loss: 0.562688752880339
epos 7 loss: 0.5688818039804944
epos 8 loss: 0.5727042324121787
epos 9 loss: 0.5747115939897727
epos 10 loss: 0.5753362019881525
epos 11 loss: 0.5749142996005654
epos 12 loss: 0.573707195731108
epos 13 loss: 0.5719177280731196
epos 14 loss: 0.5697031003488218
epos 15 loss: 0.5671849006001004
epos 16 loss: 0.5644569245120561
epos 17 loss: 0.5615912875727989
epos 18 loss: 0.558643201970253
epos 19 loss: 0.5556547107773997
epos 20 loss: 0.5526576074141039
epos 21 loss: 0.549675718249877
epos 22 loss: 0.5467266872277259
epos 23 loss: 0.5438233710242244
epos 24 loss: 0.5409749295811115
epos 25 loss: 0.5381876783587147
epos 26 loss: 0.5354657542198153
epos 27 loss: 0.5328116355616781
epos 28 loss: 0

array([[1.03216735, 3.98168131, 4.95958896, 3.7438591 , 3.01777945],
       [4.96297804, 1.01885047, 2.00367406, 4.98641149, 2.04596557],
       [3.99254632, 1.02905397, 2.01341402, 4.39543255, 1.81314811],
       [4.72243643, 3.01083417, 4.00060853, 5.57559298, 3.94881438]])

In [60]:
print('init matrix:\n', a) #1000 epos: MF normal = 0.2 loss, MF upgare = 0.05 loss

init matrix:
 [[1 4 5 0 3]
 [5 1 0 5 2]
 [4 1 2 0 0]
 [0 3 4 0 4]]
